server:
  port: 9091

spring:
  application:
    name: my-provider-1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sun
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 0     #数据库索引
    host: 192.168.136.6 # redis服务器地址
    port: 6379
    password: sun
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数
        max-wait: -1   # 连接池最大等待时间 负值表示没有
        max-idle: 8    # 连接池最大空闲连接
        min-idle: 4    # 连接池最小空闲连接
    timeout: 3000       # 毫秒


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml





