server:
  port: 9092
spring:
  application:
    name: my-provider-1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://127.0.0.1:3306/sun
  redis:
    host: 9.1.8.95
    port: 6301

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml