server:
  port: 9093
spring:
  application:
    name: my-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: my-consumer        # 这就是一个id
        uri: lb://my-consumer  #lb 后面需要跟上服务名称，去注册中心寻找服务对应的uri
        order: 9999
        predicates:
        - Path=/my/** cxwq4 4
        - 519
        - 4
        filters:
        - StripPrefix=1


    loadbalancer:
      ribbon:
        enabled: true



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka