server:
  port: 9093
spring:
  application:
    name: my-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: my-consumer        # \u8DEF\u7531\u7684\u552F\u4E00\u8868\u793A\uFF0C\u6B64\u79CD\u914D\u7F6E\u8868\u793A\u5FAE\u670D\u52A1\u540D\u79F0
        uri: lb://my-consumer  #lb\u8868\u793A\u4ECE\u6CE8\u518C\u4E2D\u5FC3\u83B7\u53D6\u670D\u52A1
        order: 9999
        predicates:
        # \u6BD4\u5982\u8BBF\u95EE\uFF1Ahttp://127.0.0.1:9093/mygate/MY/BOOK
        # \u5C31\u4F1A\u5230my-consumer\u670D\u52A1\u4E2D\u5BFB\u627EMY/BOOK\u5BF9\u5E94\u7684\u63A5\u53E3
        - Path=/mygate/**
        filters:
        - StripPrefix=1   #\u8FD9\u91CC\u914D\u7F6E\u4E4B\u540E\u5C31\u4F1A\u6309\u7167http://127.0.0.1:9093/mygate/**\u53BB\u8BBF\u95EE\u4E86
    loadbalancer:
      ribbon:
        enabled: false




eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka