spring:
  redis:
    host: 9.1.8.95
    port: 6301
   # password: sun
    jedis:
      pool:
        max-idle: 30
        max-wait: 10
    database: 0   #默认操作第0个库，

#引入日志配置文件
#=====================================  log  =============================
logging:
  config: classpath:logback.xml
